// Anagram word pools — drawn from LONG_WORDS in wordlist.js, so every
// anagram answer is guaranteed to exist in the shared dictionary.
// Training (40) and Observation (120) are non-overlapping: participants
// never see the same word twice across phases.

const ANAGRAMS_TRAINING = [
  "ABSENCE","ACCOUNT","ACTIVATE","ADAPTED","ADDITION","ADVISOR","AIRPLANE","ALPHABET",
  "AMBITION","ANALYSIS","ANCESTOR","ANNOUNCE","APPARENT","APPETITE","APPROACH","ARGUMENT",
  "ARTISTIC","ASSEMBLY","ASSISTANT","ATHLETIC","ATTITUDE","AUDIENCE","AVERAGE","AWKWARD",
  "BACKPACK","BALANCE","BANDAGE","BARGAIN","BASEBALL","BEHAVIOR","BENEFIT","BICYCLE",
  "BIRTHDAY","BLANKET","BLOSSOM","BOTANIST","BOUNDARY","BREAKFAST","BUDGET","BUILDING",
];

const ANAGRAMS_OBSERVATION = [
  "BUSINESS","CABINET","CALENDAR","CAMPAIGN","CAPACITY","CAPSULE","CAPTAIN","CARPENTER",
  "CATALOG","CATEGORY","CAUTIOUS","CELEBRATE","CENTURY","CEREMONY","CHALLENGE","CHAMPION",
  "CHARACTER","CHEMICAL","CHILDHOOD","CIRCUS","CITIZEN","CLASSIC","CLIMATE","COLLECT",
  "COLONY","COLUMN","COMBINE","COMEDY","COMFORT","COMMAND","COMMITTEE","COMPANY","COMPARE",
  "COMPASS","COMPETE","COMPLETE","COMPUTER","CONCEPT","CONCERN","CONCERT","CONDUCT",
  "CONFUSE","CONNECT","CONQUER","CONSIDER","CONSTANT","CONSTRUCT","CONSUME","CONTACT",
  "CONTAIN","CONTENT","CONTEST","CONTINUE","CONTRACT","CONTRAST","CONTROL","CONVERT",
  "CORRECT","CORRIDOR","COSTUME","COUNCIL","COUNTRY","COURAGE","CREATURE","CREDIT","CRITIC",
  "CRYSTAL","CULTURE","CURIOUS","CURTAIN","CUSTOM","CYLINDER","DANGER","DAUGHTER","DECIDE",
  "DECREASE","DEFEND","DEFINE","DELIVER","DEMAND","DENTIST","DEPART","DEPOSIT","DESERT",
  "DESIGN","DESIRE","DESTROY","DETAIL","DETECT","DEVELOP","DEVICE","DIAMOND","DIGEST",
  "DIGITAL","DILEMMA","DIRECT","DISASTER","DISCOVER","DISCUSS","DISEASE","DISPLAY",
  "DISTANCE","DISTRICT","DIVIDE","DOCTOR","DOMAIN","DOMESTIC","DONATE","DOUBLE","DRAGON",
  "DYNAMIC","ECONOMY","EDITOR","EDUCATE","ELASTIC","ELEGANT","ELEMENT","ELEPHANT","EMBRACE",
  "EMERGE",
];
